### ISSUE TITLE
process mispelled in postinstall.js - breaking install

### ISSUE THREAD

**Issue by imaffett** [Polymer/wct-local#1]
https://github.com/Polymer/wct-local/blob/master/scripts/postinstall.js#L56

This line is breaking the post install for web component tester since process is mispelled.

```
process.exit(1)
```

**Comment by oderby** [comment]
Is there a reason you didn't also create release 1.2.1 to get this change out for everyone to use? I'm still seeing this issue with a fresh npm install.

**Comment by nevir** [comment]
Ah sorry, I'll get it released

Note though that all this fixes is the final (misleading) stack trace - the actual error you're encountering will be printed just before that
