### ISSUE TITLE
Selenium does not work with Firefox

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/wct-local#24]
Upstream issue: https://github.com/SeleniumHQ/selenium/issues/2110

Currently all our Travis builds are failing as Selenium is failing to boot Firefox. This is a compatability issue with Selenium 2.53 and Firefox. When running WCT the build will fail.

This is happening on Polymer master (https://travis-ci.org/Polymer/polymer/builds/136000685#L1310) and our repositories.

Maybe it is possible to pin down Selenium until this upstream issue has been resolved?

**Comment by ryantmer** [comment]
This is an issue with Firefox 47 and Selenium 2.53.0 it seems. As a temporary fix, we just pinned the Firefox version in our .travis.yml:

```
addons:
  firefox: "46.0"
```

**Comment by benoitjchevalier** [comment]
Hi, we're hitting the same issue, just wanted to point out that it looks to me that even when this issue will be fixed the same problem might arise again with Firefox 48+ as noted in the selenium issue:
- Note : When Extension Signing ships in Firefox 48 or later the current Selenium WebDriver addon approach will no longer work and you will need to update to Marionette.

Let me know if I'm wrong thinking this, and if not are there any plan to support future Firefox versions?

**Comment by deedubbu** [comment]
As indicated in vvo/selenium-standalone/issues/181 the hotfix commit 50063065c3db97a357e67a658a1a2d0eb2e974a9 breaks runs on travis. We were running fine with pinning Firefox to version 46.0 in `.travis.yml` but now are broken on 46 and 47 because of the hotfix. Any suggestions for getting a configuration running on travis?

**Comment by wicope** [comment]
Hi all.

I have issues with [selenium 2.53.1+firefox](http://pastebin.com/8Ti36zkW) and with [selenium 2.53.1+chrome](http://pastebin.com/dHpXz5uP)

Regards.
