### ISSUE TITLE
Release 2.0.17 or 2.1

### ISSUE THREAD

**Issue by paladox** [Polymer/wct-local#73]
Hi, could 2.0.17 or 2.1 be released please?

A change was recently merged that should unlock wct usage on ci without display's.

Using chrome 59+ with headless mode.

**Comment by paladox** [comment]
cc @azakus and @justinfagnani

**Comment by justinfagnani** [comment]
I think 2.1 since it's easier to remember you need that version for headless support.

**Comment by paladox** [comment]
Ah thanks :).

Also this bumps java requirements from java 7 to java8.

**Comment by justinfagnani** [comment]
@azakus released 2.1

**Comment by paladox** [comment]
Thank you :).
