### ISSUE TITLE
Selenium / chromedriver needs upgrading to 2.15

### ISSUE THREAD

**Issue by ckortekaas** [Polymer/wct-local#8]
Hi, 

We're getting:  Error: Missing /home/rof/.nvm/v0.10.30/lib/node_modules/web-component-tester/node_modules/wct-local/node_modules/selenium-standalone/.selenium/chromedriver/2.15-x64-chromedriver

So I guess it's time to update to 2.15 to make things happy again?

Cheers,
CK

**Comment by nevir** [comment]
Yeah, and I think set it up to just read from selenium-standalone's [default versions](https://github.com/vvo/selenium-standalone/blob/master/lib/default-config.js) now that we have that

On it!

**Comment by nevir** [comment]
Fixed via `v1.4.0`
